---
configure_dotfiles: true

# Homebrew
homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - zsh
  - tig
  - pick
  - fzf
  - exa
  - bat

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - font-sauce-code-pro-nerd-font
  - meld
  - hammerspoon  

# Dotfiles
dotfiles_repo: git@github.com:kirkchen/vimrc.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/.vim
dotfiles_files:
  - .zshrc
  - .vimrc
  - .tigrc
  - .gitconfig