---
configure_dotfiles: true
configure_mac: true
configure_hammerspoon: true

# Homebrew
homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - git
  - zsh
  - tig
  - pick
  - fzf
  - exa
  - bat
  - diff-so-fancy

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - font-sauce-code-pro-nerd-font
  - meld
  - grammarly
  - visual-studio-code
  - iterm2
  - alfred

# Dotfiles
dotfiles_repo: git@github.com:kirkchen/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/.vim
dotfiles_files:
  - .zshrc
  - .vimrc
  - .tigrc
  - .gitconfig

# HammerSpoon
hammerspoon_repo: git@github.com:kirkchen/.hammerspoon.git
