---
- name: Setup Mac for development
  hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    - role: oh-my-zsh
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: terminal-setup
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: mac-setup
      when: configure_mac
      tags: ['mac']
    - role: hammerspoon
      when: configure_hammerspoon
      tags: ['hammerspoon']
