---
- name: Ensure vim submodule is up to date.
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}"
    version: "{{ dotfiles_repo_version }}"
    accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"
    recursive: yes
    update: yes
  become: false

- name: Install vim plugins.
  command: "vim +PlugInstall +qall"
  become: false